version: '3.7'

services:
  reverseproxy:
    build: .
    ports:
    - 8008:8008
    depends_on:
      - pma
      - auth
      - backend
      - engine
      - frontend

  db:
    image: remedymatch/db:latest
    environment:
    - MYSQL_ROOT_PASSWORD=root
    volumes:
    - db-data:/var/lib/mysql

  pma:
    image: hauptmedia/phpmyadmin:latest
    restart: on-failure
    environment:
    - PMA_ABSOLUTE_URI=http://localhost:8008/pma/
    - SERVER_1_HOST=db
    depends_on:
    - db

  auth:
    image: remedymatch/auth:latest
    restart: on-failure
    environment:
      - PROXY_ADDRESS_FORWARDING=true
      - DB_VENDOR=MYSQL
      - DB_ADDR=db
      - DB_DATABASE=keycloak
      - DB_USER=root
      - DB_PASSWORD=root
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/keycloak-conf/rmio_realm.json
    ports:
    - 8080:8080
    depends_on:
      - db

  backend:
    image: remedymatch/backend:latest
    restart: on-failure
    command: /bin/sh -c "sleep 30 && (redir --lport=8008 --laddr=127.0.0.1 --cport=8008 --caddr=reverseproxy &) && exec java -Dspring.profiles.active=dbinit -jar /app/spring-boot-application.jar"
    environment:
    - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/backend?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    - SPRING_DATASOURCE_DATBASE_PLATFORM=org.hibernate.dialect.MySQL8Dialect
    - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
    - SPRING_DATASOURCE_USERNAME=root
    - SPRING_DATASOURCE_PASSWORD=root
    - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
    - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://localhost:8008/auth/realms/rmio
    - IO_REMEDYMATCH_BACKEND_ENGINE_URL=http://engine:8085/engine
    - IO_REMEDYMATCH_BACKEND_GEOCODERSERVICEAPIKEY=2831cf619102d5
    depends_on:
    - db
    - auth
    - engine

  engine:
    image: remedymatch/engine:latest
    restart: on-failure
    environment:
    - CAMUNDA_BPM_ADMIN_USER_PASSWORD=admin
    - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/engine?serverTimezone=UTC
    - SPRING_DATASOURCE_DATBASE_PLATFORM=org.hibernate.dialect.MySQL5Dialect
    - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.jdbc.Driver
    - SPRING_DATASOURCE_USERNAME=root
    - SPRING_DATASOURCE_PASSWORD=root
    - SERVER_SERVLET_CONTEXT_PATH=/engine
    depends_on:
    - db

  frontend:
    image: remedymatch/frontend:latest
    restart: on-failure
    environment:
    - KEYCLOAK_REALM=rmio
    - KEYCLOAK_AUTH_SERVER_URL=http://localhost:8008/auth/
    - KEYCLOAK_RESOURCE=spring-cloud-gateway-client
    - KEYCLOAK_SSL_REQUIRED=none

volumes:
  db-data:
