version: '3.7'

services:
  reverseproxy:
    build: .
    ports:
    - 8008:8008
    depends_on:
      - auth
      - backend
      - engine
      - frontend

#  website:
#    image: remedymatch/website:latest
#    environment:
#    - APP_ENV=prod
#    - APP_SECRET=b1f80d24cc8efd80f7d6de37fb32359a406a8d15
#    - DATABASE_URL=mysql://root:root@db/website
#    - MAILER_DSN=smtp://mailcatcher
#    - ASSET_VERSION=1
#    - KEYCLOAK_URL=http://localhost:8008/auth
#    - KEYCLOAK_REALM=rmio
#    - KEYCLOAK_CLIENT_ID=admin-cli
#    - KEYCLOAK_CLIENT_SECRET=
#    - KEYCLOAK_USER=rm_website_user
#    - KEYCLOAK_PASSWORD=rm_website_user_password
#    - GOOGLE_RECAPTCHA_SECRET=6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
#    - GOOGLE_RECAPTCHA_PUBLIC=6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
#    - GOOGLE_ANALYTICS_ID=

#  pma:
#    image: hauptmedia/phpmyadmin:latest
#    environment:
#    - PMA_ABSOLUTE_URI=http://localhost:8008/pma/
#    - SERVER_1_HOST=db

#  mailcatcher:
#    image: hauptmedia/mailcatcher:latest
#    environment:
#    - MAILCATCHER_USERNAME=mailcatcher
#    - MAILCATCHER_PASSWORD=mailcatcher

  db:
    image: remedymatch/db:latest
    ports:
    - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=root
    volumes:
    - db-data:/var/lib/mysql

  auth:
    image: remedymatch/auth:latest
    restart: on-failure
    environment:
      - PROXY_ADDRESS_FORWARDING=true
      - DB_VENDOR=MYSQL
      - DB_ADDR=db
      - DB_DATABASE=keycloak
      - DB_USER=root
      - DB_PASSWORD=root
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/keycloak-conf/rmio_realm.json
    depends_on:
      - db

  backend:
    image: remedymatch/backend:latest
    restart: on-failure
    command: java -Dspring.profiles.active=prod,dbinit -jar /app/spring-boot-application.jar
    environment:
    - JWT_ISSUER_URI_REDIRECT_HOST=reverseproxy
    - JWT_ISSUER_URI_REDIRECT_PORT=8008
    - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/backend?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    - SPRING_DATASOURCE_USERNAME=root
    - SPRING_DATASOURCE_PASSWORD=root
    - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://localhost:8008/auth/realms/rmio
    - IO_REMEDYMATCH_ENGINE_REMEDYRESTAPIURL=http://engine:8085/engine/remedy
    - IO_REMEDYMATCH_ENGINE_EXTERNALTASKURL=http://engine:8085/engine/rest
    - IO_REMEDYMATCH_GEODATEN_GEOCODERSERVICEAPIKEY=2831cf619102d5
    - IO_REMEDYMATCH_KEYCLOAK_SERVERURL=http://localhost:8008/auth
    - IO_REMEDYMATCH_KEYCLOAK_USER_REALM=rmio
    - IO_REMEDYMATCH_KEYCLOAK_CLIENT_REALM=rmio
    - IO_REMEDYMATCH_KEYCLOAK_CLIENT_USERNAME=rm_backend_user
    - IO_REMEDYMATCH_KEYCLOAK_CLIENT_PASSWORD=rm_backend_user_password
    - IO_REMEDYMATCH_KEYCLOAK_CLIENT_CLIENTID=admin-cli
    - IO_REMEDYMATCH_KEYCLOAK_CLIENT_CLIENTSECRET=admin
    depends_on:
    - db
    - auth
    - engine

#  notifications:
#    image: remedymatch/notifications:latest
#    restart: on-failure
#    command: java -Dspring.profiles.active=prod -jar /app/spring-boot-application.jar
#    environment:
#    - SPRING_MAIL_HOST=BITTE_AUSFUEHLEN
#    - SPRING_MAIL_PORT=BITTE_AUSFUEHLEN
#    - SPRING_MAIL_USERNAME=BITTE_AUSFUEHLEN
#    - SPRING_MAIL_PASSWORD=BITTE_AUSFUEHLEN
#    - IO_REMEDYMATCH_ENGINE_EXTERNALTASKURL=http://engine:8085/engine/rest
#    - IO_REMEDYMATCH_FRONTEND_URL=http://www.remedymatch.io/app
#    - IO_REMEDYMATCH_KEYCLOAK_USER_REALM=rmio
#    - IO_REMEDYMATCH_WEBSITE_IMPRESSUMURL=http://www.remedymatch.io/impressum
#    - IO_REMEDYMATCH_WEBSITE_EMAILLOGOURL=http://www.remedymatch.io/assets/images/logo/mail-logo.png
#    - IO_REMEDYMATCH_EMAIL_FROM=bittenichtantworten@remedymatch.io
#    depends_on:
#    - engine

  engine:
    image: remedymatch/engine:latest
    restart: on-failure
    environment:
    - CAMUNDA_BPM_ADMIN_USER_PASSWORD=admin
    - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/engine?serverTimezone=UTC
    - SPRING_DATASOURCE_USERNAME=root
    - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
    - db

  frontend:
    image: remedymatch/frontend:latest
    restart: on-failure
    environment:
    - KEYCLOAK_REALM=rmio
    - KEYCLOAK_AUTH_SERVER_URL=http://localhost:8008/auth/
    - KEYCLOAK_RESOURCE=spring-cloud-gateway-client
    - KEYCLOAK_SSL_REQUIRED=external

# for local development ubuntu
#
#  frontend:
#    image: node:10
#    restart: on-failure
#    command: /bin/sh -c "yarn && yarn run start"
#    working_dir: /app
#    tty: true
#    volumes:
#    - ../rm-frontend:/app
#    environment:
#    - KEYCLOAK_REALM=rmio
#    - KEYCLOAK_AUTH_SERVER_URL=http://localhost:8008/auth/
#    - KEYCLOAK_RESOURCE=spring-cloud-gateway-client
#    - KEYCLOAK_SSL_REQUIRED=external

volumes:
  db-data:
